name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-unix:
    name: UNIX Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ "ubuntu-latest", "macos-latest", ]
        python-version: [ "3.7", "3.8" ]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cdtea-env
          environment-file: environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Install dependencies
        run: |
          conda env list
          conda info
      - name: Run Test Suite
        run: |
          pytest --cov=./cdtea --cov-report=xml
      - name: Check Coverage Output
        run: |
          ls -a
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
          files: coverage.xml

  build-win:
    name: WIN Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ "windows-latest" ]
        python-version: [ "3.7", "3.8" ]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cdtea-env
          environment-file: environment.yml
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: Install dependencies
        run: |
          conda env list
          conda info
      - name: Run Test Suite
        run: |
          pytest --cov=cdtea --cov-report=xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
          files: coverage.xml